### ISSUE TITLE
执行 actions 提示缺少参数的错误

### ISSUE THREAD

**Issue by oppih** [yihong0618/duolingo_remember#2]
你好，我已在 Secrets 中设置了我的 TELE_TOKEN TELE_CHAT_ID 等参数，并且 LATEST_WORDS_NUMBER 也未做修改，但是执行 action 时出现下面的错误：

```
usage: duolingo.py [-h]
10
                   duolingo_user_name duolingo_password tele_token
11
                   tele_chat_id latest_number
12
duolingo.py: error: the following arguments are required: tele_chat_id, latest_number
13
Error: Process completed with exit code 2.
```

提示缺少了后面两个参数，看了实现代码不知道原因，能否检查一下？谢谢

**Comment by yihong0618** [comment]
@oppih 
请看一下是不是没在 secret 中设置多邻国的账号和密码。
 
![image](https://user-images.githubusercontent.com/15976103/104974277-5f612a00-5a32-11eb-8844-fe174c804b9e.png)

**Comment by oppih** [comment]
四个都设置了的，所以就有点奇怪，四个设置单单没读到这一个 chat_id ，并且env是配置在yml里面的也没读取到。

**Comment by yihong0618** [comment]
@oppih 

你能看下名字是否完全一致么和下面这个四个。
![image](https://user-images.githubusercontent.com/15976103/104987067-bf19fe00-5a4f-11eb-84b4-6b8f6e6552b3.png)

不一定是 chatid, 这个机制是按顺序读取。

你可以本地跑一下试试
python  duolingo.py a b c d e

**Comment by yihong0618** [comment]
@oppih 

我找了个其它的号 fork 跑了下应该没问题。
你的 duolingo name 或 password 是否有空格之类的特殊符号？

**Comment by oppih** [comment]
都没特殊，并且还都是复制了去贴的secrets。所以我就很奇怪地来开issue了。等今天下班回去本地跑一下再试试

**Comment by oppih** [comment]
本地运行成功后，再把参数贴到secrets里面，可以执行了，那应该是我之前复制粘贴出现问题，感谢答复。

**Comment by yihong0618** [comment]
> 行成功后，再把参数贴到secrets里面，可以执行了，那应该是我之前复制粘贴出现问题，感谢答复。

好的。
