### ISSUE TITLE
Github action error

### ISSUE THREAD

**Issue by wsycqyz** [yihong0618/duolingo_remember#8]
Telegram can receive 5 message: new words, new article, new article trans, new_word.mp3 and new_article.mp3.
Check Github action log, see below error:

![image](https://user-images.githubusercontent.com/1931001/234744711-987632cc-15e5-4f42-82a9-353571ed4ca9.png)

**Comment by yihong0618** [comment]
@wsycqyz seems ok now

**Comment by wsycqyz** [comment]
Did not see the issue now.
